### ISSUE TITLE
Add a news/update section to the landing page

### ISSUE THREAD

**Issue by primalpop** [zotbins/zotbins.github.io#2]

**Comment by caojoshua** [comment]
linked to blog. is that good enough?

**Comment by primalpop** [comment]
The blog is more of a slow moving giant. I was mentioning more like a news update such as "Presented at SCWG" or "Completed 70th group meeting" or "Recruited 3 more members to ZOWA" etc.

**Comment by jessechong** [comment]
I think this is a good idea-- we should continue developing this feature.

Btw, I think this is what Primal meant: should be a very quick bullet point news feed that publicizes when things are happening. E.g., "our members graduated today", "we recruited 3 new members today", "presented to this meeting", etc. Please check the attached screenshot... it's a rough mock-up I made.

I think that it should be a box with a scroll bar so that it doesn't take up so much space. We should definitely link the Blog, maybe at the very bottom/outside of the scroll-bar-box.

![image](https://user-images.githubusercontent.com/44284982/95029959-e398c880-0660-11eb-8530-84894f60fc39.png)

We can also do something like this if we want it to look nicer. Kind of a mini-timeline would be cool with the dots

![image](https://user-images.githubusercontent.com/44284982/95030021-49855000-0661-11eb-9718-e84ed4e1d91a.png)

**Comment by jessechong** [comment]
Needs to be improved a bit more, but its fine for now. Thanks for the hard work Palak! :)
